version: "3.5"

volumes:
  db-data:
    driver: local

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: throat
      POSTGRES_PASSWORD: dev
      POSTGRES_DATABASE: throat
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
  throat:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/throat
    environment:
      # Configs set here will override your config.yaml
      APP_HOST: 0.0.0.0
      APP_REDIS_URL: redis://redis:6379
      CACHE_REDIS_URL: redis://redis:6379
      DATABASE_ENGINE: PostgresqlDatabase
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: throat
      DATABASE_PASSWORD: dev
      DATABASE_NAME: throat
      DATABASE_AUTOCOMMIT: "true"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  migration:
    image: throat_throat
    command: ["python3", "throat.py", "migration", "apply"]
    environment:
      DATABASE_ENGINE: PostgresqlDatabase
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: throat
      DATABASE_PASSWORD: dev
      DATABASE_NAME: throat
      DATABASE_AUTOCOMMIT: "true"
    volumes:
      - ./config.yaml:/throat/config.yaml
      - ./migrations:/throat/migrations
    depends_on:
      - db
    restart: on-failure
