site:
  name: 'čekni.to'
  # Lema shown in the page's title
  lema: 'čekni.to: homepage tvojho internetu'
  # Copyright line shown in the footer
  copyright: 'LenOn Productions'

  # Name shown when a sub is owned by a deleted account or abandoned
  placeholder_account: '[checkedout]'

  # Prefix for subs (by default it's 's').
  # It can be anything EXCEPT 'u', 'c' or 'p'
  sub_prefix: 's'

  # Allow everybody to upload files
  # (by default it's only admins and users authorized through a metadata key)
  allow_uploads: False

  # Amount of time in seconds the post author can edit a post's title after the post
  # was created. Set to zero to disable title editing (default is 5 minutes)
  title_edit_timeout: 300

  # If True, enables setting security questions on the admin page. 
  # Users will be asked to answer one of these security questions before registering
  enable_security_question: False

app:
  # URL to a working redis server.
  # Used for websockets and caching (if enabled)
  redis_url: 'redis://127.0.0.1:6379'

  # Secret key used to encrypt session cookies.
  # You can generate one by using `os.urandom(24)`
  # ///// YOU MUST CHANGE THIS VALUE \\\\\
  secret_key: 'PUT SOMETHING HERE'

  # Enables debug mode. Always set to False in a production environment
  debug: True

  # This will make all captchas valid, disable caching and rate limits
  # Always set to False in a production environment
  testing: True

  # Available languages for users to select. This will also be used when trying to guess
  # the user's language.
  languages:
  # - en
    - sk

  # Fallback language when there is no accept-language header sent by the browser
  fallback_language: 'sk'


cache:
  # Caching strategy to use.
  # Recommended values:
  # - 'null' (no caching)
  # - 'redis' (recommended)
  # - 'simple' (only for testing)
  type: 'redis'

sendgrid:
  # At the moment this is only used to send password recovery
  # emails.
  # SendGrid API key
  api_key: '...'
  # Sender address
  default_from: 'noreply@cekni.to'

storage:
  thumbnails:
    # Path where thumbnails will be stored (app MUST have write access)
    path: './app/static/thumbs'
    # URL or relative path where thumbnails are served (must end with forward slash). If hosting on the same domain, URL should also have 'static' in it, e.g.  'http://192.168.0.82/static/thumbs/'
    url: 'https://uploads.itworks.sk/thumbs/'
  
  uploads:
    # Same rules as thumbnails
    path: './app/static/ups'
    url: 'https://uploads.itworks.sk/ups/'

database:
  # Database engine. Possible values:
  # - MySQLDatabase
  # - PostgresqlDatabase
  # - SqliteDatabase (untested)
  engine: 'PostgresqlDatabase'
  
  # Parameters for both MySQL and postgres
  host: 'localhost'
  port: 5432
  #user: 'polsaker'
  #password: 'throat'
  # Database name
  #name: 'phuks'

  # For sqlite:
  #database: '/path/to/sqlite.db'
  
  # Uncomment if using Postgres:
  autocommit: True

  # Uncomment if using MySQL
  #charset: 'utf8mb4'
