#!/usr/bin/env python3
"""
Complete Flask translations.json with ALL Lemmy languages (30+).
Only adds missing keys, never overwrites existing ones.
Also copies about_topic keys from custom-translations.json where available.
"""
import json

with open('translations.json', 'r') as f:
    data = json.load(f)

# Load custom-translations.json to copy about_topic keys
import os
custom_path = '/home/user/Oratio/lemmy-ui-custom/custom-translations.json'
with open(custom_path, 'r') as f:
    custom = json.load(f)

FULL = {

# ============================================================
# JAPANESE (ja) - fill remaining ~17 keys
# ============================================================
"ja": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Bitcoin Cash 決済サービス",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH)はBitcoinの分岐で、本来のピアツーピア電子マネーのビジョンを維持しています。低い手数料で高速な取引が可能です。",
    "help_install_wallet_desc": "Bitcoin Cashウォレットはこちらからダウンロードできます：<a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a>（PC向け）または<a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a>（モバイル向け）",
    "help_getting_bch_desc": "ATMや個人取引でBitcoin Cashを入手できます。<a href=\"https://coinatmradar.com\" target=\"_blank\">CoinATMRadar</a>で最寄りのATMを探せます。",
    "help_mixing_desc_1": "次のシンボルを右クリックしてください：",
    "help_mixing_desc_2": "高速で効果的なミキシングのため、これらの設定を行ってください：",
    "help_mixing_desc_3": "ミックス済みの出力のみ使用する設定を有効にしてください：",
    "invoice_send_to": "正確に<span style=\"color: #667eea;\">{{amount}} BCH</span>を以下のアドレスに送信してください",
    "success_tx_view": "Blockchairでトランザクションの詳細を確認",
    "success_premium_desc": "5倍の投票力、💰ゴールドバッジ、広告なし体験、メンバー専用フィード",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# CHINESE (zh) - fill remaining ~24 keys
# ============================================================
"zh": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Bitcoin Cash 支付服务",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH)是比特币的分支，保留了点对点电子现金的原始愿景。手续费低，交易快速。",
    "help_install_wallet_desc": "你可以在这里下载Bitcoin Cash钱包：<a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a>（桌面版）或<a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a>（手机版）",
    "help_getting_bch_desc": "你可以通过ATM或私人交易获取Bitcoin Cash。在<a href=\"https://coinatmradar.com\" target=\"_blank\">CoinATMRadar</a>查找附近的ATM。",
    "help_mixing_desc_1": "右键点击以下符号：",
    "help_mixing_desc_2": "设置以下配置以实现快速有效的混币：",
    "help_mixing_desc_3": "启用仅使用混合后的输出设置：",
    "invoice_send_to": "请将<span style=\"color: #667eea;\">{{amount}} BCH</span>发送到以下地址",
    "success_tx_view": "点击在Blockchair查看交易详情",
    "success_premium_desc": "5倍投票权、💰金牌徽章、无广告体验、会员专属动态",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# GERMAN (de) - fill remaining ~40 keys
# ============================================================
"de": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Bitcoin Cash Zahlungsservice",
    "generate_invoice_desc": "Nur für Entwicklungs- und Testzwecke.",
    "amount_min": "Mindestbetrag: 0.0001 BCH",
    "credit_info": "Guthaben wird nach Zahlung deinem Konto gutgeschrieben",
    "not_logged_in_warning": "⚠️ Nicht eingeloggt: Bitte zuerst auf oratio.space einloggen",
    "no_login_warning": "Ohne Login keine Zahlungsvorteile",
    "help_title": "🛈 Bitcoin Cash Hilfe (Sei deine eigene Bank)",
    "help_what_is_bch": "Was ist Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) ist ein Ableger von Bitcoin, der die ursprüngliche Vision von elektronischem Peer-to-Peer-Bargeld bewahrt.",
    "help_install_wallet": "Wallet installieren",
    "help_install_wallet_desc": "Du kannst ein Bitcoin Cash Wallet hier herunterladen: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (Desktop) oder <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (Mobil)",
    "help_getting_bch": "Bitcoin Cash erhalten",
    "help_getting_bch_desc": "Du kannst Bitcoin Cash an ATMs oder durch Privathandel erhalten.",
    "help_mixing": "Bitcoin Cash mischen/privatisieren",
    "help_mixing_desc_1": "Rechtsklicke auf das folgende Symbol:",
    "help_mixing_desc_2": "Richte diese Einstellungen ein:",
    "help_mixing_desc_3": "Nur gemischte Ausgaben verwenden:",
    "generate_invoice_title": "🎫 Zahlungsrechnung erstellen",
    "invoice_nonrefundable_title": "Keine Erstattung",
    "invoice_nonrefundable_desc": "Alle Zahlungen sind nicht erstattungsfähig. Bitte Betrag und Adresse vor der Zahlung prüfen.",
    "invoice_membership_title": "Jahresmitgliedschaft — $5 USD/Jahr",
    "invoice_membership_desc": "5× Stimmkraft, 💰 Gold-Abzeichen, werbefrei, Mitglieder-Feed",
    "invoice_tx_label": "🔗 Transaktion:",
    "invoice_send_to": "Sende genau <span style=\"color: #667eea;\">{{amount}} BCH</span> an diese Adresse",
    "invoice_qr_title": "📱 QR-Code scannen zum Bezahlen",
    "error_resolve_title": "Lösungsvorschläge",
    "error_resolve_1": "Seite aktualisieren und erneut versuchen",
    "error_resolve_2": "Kurz warten und erneut versuchen",
    "error_resolve_3": "Bei anhaltendem Problem den Support kontaktieren",
    "error_resolve_4": "Internetverbindung überprüfen",
    "success_confirmed_desc": "Bitcoin Cash-Zahlung auf der Blockchain bestätigt",
    "success_tx_view": "Transaktionsdetails auf Blockchair ansehen",
    "success_premium_desc": "5× Stimmkraft, 💰 Gold-Abzeichen, werbefrei, Mitglieder-Feed",
    "success_note_1": "• Diese Zahlung ist nicht erstattungsfähig",
    "success_note_2": "• Transaktions-Hash als Zahlungsnachweis aufbewahren",
    "success_note_3": "• Jahresmitgliedschaft ($5/Jahr) über die Wallet-Seite kaufen",
    "success_note_4": "• Bei Fragen den oratio-Support kontaktieren",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# FRENCH (fr) - fill remaining ~46 keys
# ============================================================
"fr": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Service de Paiement Bitcoin Cash",
    "generate_invoice_desc": "Pour développement et test uniquement.",
    "amount_min": "Montant minimum : 0.0001 BCH",
    "amount_label": "Montant (BCH)",
    "username_label": "Nom d'utilisateur",
    "credit_info": "Les crédits seront ajoutés après le paiement",
    "not_logged_in_warning": "⚠️ Non connecté : Veuillez d'abord vous connecter sur oratio.space",
    "no_login_warning": "Sans connexion, pas de bénéfices de paiement",
    "help_title": "🛈 Aide Bitcoin Cash (Soyez votre propre banque)",
    "help_what_is_bch": "Qu'est-ce que Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) est une branche de Bitcoin qui conserve la vision originale de monnaie électronique pair-à-pair.",
    "help_install_wallet": "Installer un portefeuille",
    "help_install_wallet_desc": "Téléchargez un portefeuille Bitcoin Cash : <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (bureau) ou <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (mobile)",
    "help_getting_bch": "Obtenir Bitcoin Cash",
    "help_getting_bch_desc": "Vous pouvez obtenir du BCH aux distributeurs ATM ou par échange privé.",
    "help_mixing": "Mélanger/privatiser votre Bitcoin Cash",
    "help_mixing_desc_1": "Clic droit sur le symbole suivant :",
    "help_mixing_desc_2": "Configurez ces paramètres pour un mélange rapide :",
    "help_mixing_desc_3": "Utilisez uniquement les sorties mélangées :",
    "generate_invoice_title": "🎫 Générer une facture de paiement",
    "nonrefundable_title": "Important : Politique de non-remboursement",
    "nonrefundable_desc": "Tous les paiements en Bitcoin Cash sont <strong>non remboursables</strong>.",
    "nonrefundable_1": "• Vérifiez le montant et l'adresse avant le paiement",
    "nonrefundable_2": "• Les dépôts ne sont pas remboursables pour raisons de sécurité",
    "nonrefundable_3": "• Procéder au paiement implique l'acceptation de cette politique",
    "invoice_nonrefundable_title": "Politique de non-remboursement",
    "invoice_nonrefundable_desc": "Tous les paiements sont non remboursables.",
    "invoice_membership_title": "Abonnement annuel — $5 USD/an",
    "invoice_membership_desc": "5× pouvoir de vote, 💰 badge Or, sans publicité, fil membres",
    "invoice_tx_label": "🔗 Transaction :",
    "invoice_send_to": "Envoyez exactement <span style=\"color: #667eea;\">{{amount}} BCH</span> à cette adresse",
    "invoice_qr_title": "📱 Scannez le QR code pour payer",
    "error_resolve_title": "Comment résoudre",
    "error_resolve_1": "Rafraîchir la page et réessayer",
    "error_resolve_2": "Attendre un moment et réessayer",
    "error_resolve_3": "Si le problème persiste, contacter le support",
    "error_resolve_4": "Vérifier votre connexion internet",
    "success_confirmed_desc": "Paiement Bitcoin Cash confirmé sur la blockchain",
    "success_tx_view": "Voir les détails de la transaction sur Blockchair",
    "success_premium_desc": "5× pouvoir de vote, 💰 badge Or, sans publicité, fil membres",
    "success_note_1": "• Ce paiement n'est pas remboursable",
    "success_note_2": "• Conservez le hash de transaction comme preuve",
    "success_note_3": "• Achetez l'abonnement annuel ($5/an) depuis votre portefeuille",
    "success_note_4": "• Contactez le support oratio pour toute question",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# SPANISH (es) - fill remaining ~46 keys
# ============================================================
"es": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Servicio de Pago Bitcoin Cash",
    "generate_invoice_desc": "Solo para desarrollo y pruebas.",
    "amount_min": "Monto mínimo: 0.0001 BCH",
    "amount_label": "Monto (BCH)",
    "username_label": "Nombre de usuario",
    "credit_info": "Los créditos se añadirán después del pago",
    "not_logged_in_warning": "⚠️ No conectado: Inicia sesión primero en oratio.space",
    "no_login_warning": "Sin inicio de sesión no hay beneficios de pago",
    "help_title": "🛈 Ayuda Bitcoin Cash (Sé tu propio banco)",
    "help_what_is_bch": "Qué es Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) es una bifurcación de Bitcoin que mantiene la visión original de dinero electrónico peer-to-peer.",
    "help_install_wallet": "Instalar una billetera",
    "help_install_wallet_desc": "Descarga una billetera Bitcoin Cash: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (escritorio) o <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (móvil)",
    "help_getting_bch": "Obtener Bitcoin Cash",
    "help_getting_bch_desc": "Puedes obtener BCH en cajeros ATM o intercambio privado.",
    "help_mixing": "Mezclar/privatizar tu Bitcoin Cash",
    "help_mixing_desc_1": "Haz clic derecho en el siguiente símbolo:",
    "help_mixing_desc_2": "Configura estos ajustes para mezcla rápida:",
    "help_mixing_desc_3": "Usar solo salidas mezcladas:",
    "generate_invoice_title": "🎫 Generar factura de pago",
    "nonrefundable_title": "Importante: Política de no reembolso",
    "nonrefundable_desc": "Todos los pagos en Bitcoin Cash son <strong>no reembolsables</strong>.",
    "nonrefundable_1": "• Verifica el monto y la dirección antes del pago",
    "nonrefundable_2": "• Los depósitos no son reembolsables por razones de seguridad",
    "nonrefundable_3": "• Proceder con el pago implica aceptar esta política",
    "invoice_nonrefundable_title": "Política de no reembolso",
    "invoice_nonrefundable_desc": "Todos los pagos son no reembolsables.",
    "invoice_membership_title": "Membresía anual — $5 USD/año",
    "invoice_membership_desc": "5× poder de voto, 💰 insignia Oro, sin anuncios, feed de miembros",
    "invoice_tx_label": "🔗 Transacción:",
    "invoice_send_to": "Envía exactamente <span style=\"color: #667eea;\">{{amount}} BCH</span> a esta dirección",
    "invoice_qr_title": "📱 Escanea el QR para pagar",
    "error_resolve_title": "Cómo resolver",
    "error_resolve_1": "Actualizar la página y reintentar",
    "error_resolve_2": "Esperar un momento y reintentar",
    "error_resolve_3": "Si persiste, contactar soporte",
    "error_resolve_4": "Verificar conexión a internet",
    "success_confirmed_desc": "Pago Bitcoin Cash confirmado en la blockchain",
    "success_tx_view": "Ver detalles de la transacción en Blockchair",
    "success_premium_desc": "5× poder de voto, 💰 insignia Oro, sin anuncios, feed de miembros",
    "success_note_1": "• Este pago no es reembolsable",
    "success_note_2": "• Guarda el hash de transacción como comprobante",
    "success_note_3": "• Compra la membresía anual ($5/año) desde tu cartera",
    "success_note_4": "• Contacta al soporte de oratio",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# RUSSIAN (ru) - fill remaining ~46 keys
# ============================================================
"ru": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Платёжный сервис Bitcoin Cash",
    "generate_invoice_desc": "Только для разработки и тестирования.",
    "amount_min": "Минимальная сумма: 0.0001 BCH",
    "amount_label": "Сумма (BCH)",
    "username_label": "Имя пользователя",
    "credit_info": "Кредиты будут зачислены после оплаты",
    "not_logged_in_warning": "⚠️ Не авторизован: Сначала войдите на oratio.space",
    "no_login_warning": "Без авторизации нет платёжных привилегий",
    "help_title": "🛈 Помощь по Bitcoin Cash (Будь своим банком)",
    "help_what_is_bch": "Что такое Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) — это ответвление Bitcoin, сохраняющее оригинальное видение пиринговых электронных денег.",
    "help_install_wallet": "Установка кошелька",
    "help_install_wallet_desc": "Скачайте кошелёк Bitcoin Cash: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (ПК) или <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (мобильный)",
    "help_getting_bch": "Получение Bitcoin Cash",
    "help_getting_bch_desc": "BCH можно получить через ATM или частный обмен.",
    "help_mixing": "Микширование/приватность Bitcoin Cash",
    "help_mixing_desc_1": "Нажмите правой кнопкой на следующий символ:",
    "help_mixing_desc_2": "Настройте параметры для быстрого микширования:",
    "help_mixing_desc_3": "Используйте только смешанные выходы:",
    "generate_invoice_title": "🎫 Создать платёжный счёт",
    "nonrefundable_title": "Важно: Политика невозврата",
    "nonrefundable_desc": "Все платежи в Bitcoin Cash <strong>не подлежат возврату</strong>.",
    "nonrefundable_1": "• Проверьте сумму и адрес перед оплатой",
    "nonrefundable_2": "• Депозиты не возвращаются по соображениям безопасности",
    "nonrefundable_3": "• Совершая платёж, вы соглашаетесь с этой политикой",
    "invoice_nonrefundable_title": "Политика невозврата",
    "invoice_nonrefundable_desc": "Все платежи не подлежат возврату.",
    "invoice_membership_title": "Годовая подписка — $5 USD/год",
    "invoice_membership_desc": "5× сила голоса, 💰 золотой значок, без рекламы, лента подписчиков",
    "invoice_tx_label": "🔗 Транзакция:",
    "invoice_send_to": "Отправьте ровно <span style=\"color: #667eea;\">{{amount}} BCH</span> на этот адрес",
    "invoice_qr_title": "📱 Сканируйте QR-код для оплаты",
    "error_resolve_title": "Как решить",
    "error_resolve_1": "Обновите страницу и повторите",
    "error_resolve_2": "Подождите и повторите",
    "error_resolve_3": "Если проблема не исчезает, свяжитесь с поддержкой",
    "error_resolve_4": "Проверьте подключение к интернету",
    "success_confirmed_desc": "Платёж Bitcoin Cash подтверждён в блокчейне",
    "success_tx_view": "Просмотреть детали транзакции на Blockchair",
    "success_premium_desc": "5× сила голоса, 💰 золотой значок, без рекламы, лента подписчиков",
    "success_note_1": "• Этот платёж не подлежит возврату",
    "success_note_2": "• Сохраните хеш транзакции как подтверждение оплаты",
    "success_note_3": "• Купите годовую подписку ($5/год) со страницы кошелька",
    "success_note_4": "• По вопросам обращайтесь в поддержку oratio",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# PORTUGUESE (pt) - fill remaining ~75 keys
# ============================================================
"pt": {
    "nonrefundable_desc": "Todos os pagamentos em Bitcoin Cash são <strong>não reembolsáveis</strong>.",
    "nonrefundable_1": "• Verifique o montante e o endereço antes do pagamento",
    "nonrefundable_2": "• Depósitos não são reembolsáveis por razões de segurança",
    "nonrefundable_3": "• Prosseguir com o pagamento implica aceitar esta política",
    "premium_title": "💎 Benefícios Premium",
    "premium_price": "Subscrição anual — apenas $5 USD/ano em BCH",
    "benefit_voting": "🗳️ <strong>5× Poder de Voto</strong>",
    "benefit_visibility": "📈 <strong>Visibilidade Instantânea</strong>",
    "benefit_badge": "💰 <strong>Badge de Ouro</strong>",
    "benefit_adfree": "🚫 <strong>Sem Publicidade</strong>",
    "benefit_feed": "⭐ <strong>Feed Exclusivo de Membros</strong>",
    "bch_help_btn": "🛈 Ajuda BCH Bitcoin Cash",
    "generate_invoice_desc": "Apenas para desenvolvimento e testes.",
    "amount_label": "Montante (BCH)",
    "amount_min": "Montante mínimo: 0.0001 BCH",
    "username_label": "Nome de utilizador",
    "credit_info": "Os créditos serão adicionados após o pagamento",
    "not_logged_in_warning": "⚠️ Não autenticado: Faça login primeiro em oratio.space",
    "no_login_warning": "Sem login não há benefícios de pagamento",
    "footer_desc": "Pagamentos seguros e transparentes em criptomoeda",
    "help_title": "🛈 Ajuda Bitcoin Cash (Seja o seu próprio banco)",
    "help_what_is_bch": "O que é Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) é um ramo do Bitcoin que mantém a visão original de dinheiro eletrónico peer-to-peer.",
    "help_install_wallet": "Instalar uma carteira",
    "help_install_wallet_desc": "Descarregue uma carteira Bitcoin Cash: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (PC) ou <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (telemóvel)",
    "help_getting_bch": "Obter Bitcoin Cash",
    "help_getting_bch_desc": "Pode obter BCH em ATMs ou através de troca privada.",
    "help_mixing": "Misturar/privatizar o seu Bitcoin Cash",
    "help_mixing_desc_1": "Clique com o botão direito no seguinte símbolo:",
    "help_mixing_desc_2": "Configure estas definições para mistura rápida:",
    "help_mixing_desc_3": "Use apenas saídas misturadas:",
    "payment_home_btn": "💳 Serviço de Pagamento",
    "go_to_oratio_btn": "🏠 Ir para oratio",
    "invoice_nonrefundable_title": "Política de Não Reembolso",
    "invoice_nonrefundable_desc": "Todos os pagamentos são não reembolsáveis.",
    "invoice_membership_title": "Subscrição anual — $5 USD/ano",
    "invoice_membership_desc": "5× poder de voto, 💰 badge Ouro, sem publicidade, feed de membros",
    "invoice_payment_title": "💳 Pagamento Bitcoin Cash",
    "invoice_id_label": "📋 ID da Fatura:",
    "invoice_amount_label": "💰 Montante do Pagamento:",
    "invoice_status_label": "📊 Estado:",
    "invoice_tx_label": "🔗 Transação:",
    "invoice_send_to": "Envie exatamente <span style=\"color: #667eea;\">{{amount}} BCH</span> para este endereço",
    "invoice_copy_btn": "📋 Copiar",
    "invoice_qr_title": "📱 Digitalize o código QR para pagar",
    "invoice_check_btn": "🔍 Verificar Estado do Pagamento",
    "invoice_back_btn": "🏠 Voltar",
    "invoice_checking": "A verificar...",
    "invoice_check_again": "Verificar novamente",
    "invoice_check_failed": "Verificação falhou",
    "invoice_address_copied": "Endereço copiado",
    "error_title": "Algo correu mal!",
    "error_message_label": "Mensagem de Erro",
    "error_resolve_title": "Como resolver",
    "error_resolve_1": "Atualizar a página e tentar novamente",
    "error_resolve_2": "Esperar um momento e tentar novamente",
    "error_resolve_3": "Se persistir, contactar suporte",
    "error_resolve_4": "Verificar a ligação à internet",
    "success_title": "Pagamento Concluído com Sucesso!",
    "success_confirmed_title": "Pagamento Confirmado",
    "success_confirmed_desc": "Pagamento Bitcoin Cash confirmado na blockchain",
    "success_invoice_id": "📋 ID da Fatura",
    "success_tx_hash": "🔗 Hash da Transação",
    "success_tx_view": "Ver detalhes da transação no Blockchair",
    "success_amount": "💰 Montante do Pagamento",
    "success_credit_title": "💰 Crédito Adicionado à Conta",
    "success_credit_desc": "foi adicionado com sucesso à sua conta.",
    "success_credit_balance": "Saldo atual:",
    "success_premium_title": "🎉 Benefícios Premium Ativados!",
    "success_premium_desc": "5× poder de voto, 💰 badge Ouro, sem publicidade, feed de membros",
    "success_notes_title": "📌 Notas Importantes:",
    "success_note_1": "• Este pagamento não é reembolsável",
    "success_note_2": "• Guarde o hash da transação como comprovativo",
    "success_note_3": "• Compre a subscrição anual ($5/ano) na página da carteira",
    "success_note_4": "• Contacte o suporte do oratio para questões",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# PORTUGUESE BRAZIL (pt_BR) - full
# ============================================================
"pt_BR": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Serviço de Pagamento Bitcoin Cash",
    "nonrefundable_title": "Importante: Política de Não Reembolso",
    "nonrefundable_desc": "Todos os pagamentos em Bitcoin Cash são <strong>não reembolsáveis</strong>.",
    "nonrefundable_1": "• Verifique o valor e o endereço antes do pagamento",
    "nonrefundable_2": "• Depósitos não são reembolsáveis por razões de segurança",
    "nonrefundable_3": "• Prosseguir com o pagamento implica aceitar esta política",
    "premium_title": "💎 Benefícios Premium",
    "premium_price": "Assinatura anual — apenas $5 USD/ano em BCH",
    "benefit_voting": "🗳️ <strong>5× Poder de Voto</strong>",
    "benefit_visibility": "📈 <strong>Visibilidade Instantânea</strong>",
    "benefit_badge": "💰 <strong>Badge de Ouro</strong>",
    "benefit_adfree": "🚫 <strong>Sem Anúncios</strong>",
    "benefit_feed": "⭐ <strong>Feed Exclusivo de Membros</strong>",
    "bch_help_btn": "🛈 Ajuda BCH Bitcoin Cash",
    "return_home": "🏠 Voltar ao oratio.space",
    "generate_invoice_title": "🎫 Gerar Fatura de Pagamento",
    "generate_invoice_desc": "Apenas para desenvolvimento e testes.",
    "amount_label": "Valor (BCH)",
    "amount_min": "Valor mínimo: 0.0001 BCH",
    "username_label": "Nome de usuário",
    "please_login": "Faça login primeiro",
    "not_logged_in": "Não conectado",
    "logged_in_as": "✓ Conectado como:",
    "credit_info": "Os créditos serão adicionados após o pagamento",
    "not_logged_in_warning": "⚠️ Não conectado: Faça login primeiro no oratio.space",
    "no_login_warning": "Sem login você não pode receber benefícios",
    "generate_invoice_btn": "🚀 Gerar Fatura",
    "login_required_btn": "🔒 Login Necessário",
    "footer_copyright": "© 2026 oratio - Sistema de Pagamento Bitcoin Cash",
    "footer_desc": "Pagamentos seguros e transparentes em criptomoeda",
    "help_title": "🛈 Ajuda Bitcoin Cash (Seja seu próprio banco)",
    "help_what_is_bch": "O que é Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) é uma ramificação do Bitcoin que mantém a visão original de dinheiro eletrônico peer-to-peer.",
    "help_install_wallet": "Instalando uma carteira",
    "help_install_wallet_desc": "Baixe uma carteira Bitcoin Cash: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (desktop) ou <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (celular)",
    "help_getting_bch": "Obtendo Bitcoin Cash",
    "help_getting_bch_desc": "Você pode obter BCH em ATMs ou por troca privada.",
    "help_mixing": "Misturar/privatizar seu Bitcoin Cash",
    "help_mixing_desc_1": "Clique com o botão direito no seguinte símbolo:",
    "help_mixing_desc_2": "Configure essas opções para mistura rápida:",
    "help_mixing_desc_3": "Use apenas saídas misturadas:",
    "payment_home_btn": "💳 Serviço de Pagamento",
    "go_to_oratio_btn": "🏠 Ir para o oratio",
    "invoice_nonrefundable_title": "Política de Não Reembolso",
    "invoice_nonrefundable_desc": "Todos os pagamentos não são reembolsáveis.",
    "invoice_membership_title": "Assinatura anual — $5 USD/ano",
    "invoice_membership_desc": "5× poder de voto, 💰 badge Ouro, sem anúncios, feed de membros",
    "invoice_payment_title": "💳 Pagamento Bitcoin Cash",
    "invoice_id_label": "📋 ID da Fatura:",
    "invoice_amount_label": "💰 Valor do Pagamento:",
    "invoice_status_label": "📊 Status:",
    "invoice_tx_label": "🔗 Transação:",
    "invoice_send_to": "Envie exatamente <span style=\"color: #667eea;\">{{amount}} BCH</span> para este endereço",
    "invoice_copy_btn": "📋 Copiar",
    "invoice_qr_title": "📱 Escaneie o QR para pagar",
    "invoice_check_btn": "🔍 Verificar Status do Pagamento",
    "invoice_back_btn": "🏠 Voltar",
    "invoice_checking": "Verificando...",
    "invoice_check_again": "Verificar novamente",
    "invoice_check_failed": "Verificação falhou",
    "invoice_address_copied": "Endereço copiado",
    "error_title": "Algo deu errado!",
    "error_message_label": "Mensagem de Erro",
    "error_resolve_title": "Como resolver",
    "error_resolve_1": "Atualize a página e tente novamente",
    "error_resolve_2": "Espere um momento e tente novamente",
    "error_resolve_3": "Se persistir, entre em contato com o suporte",
    "error_resolve_4": "Verifique sua conexão com a internet",
    "success_title": "Pagamento Concluído com Sucesso!",
    "success_confirmed_title": "Pagamento Confirmado",
    "success_confirmed_desc": "Pagamento Bitcoin Cash confirmado na blockchain",
    "success_invoice_id": "📋 ID da Fatura",
    "success_tx_hash": "🔗 Hash da Transação",
    "success_tx_view": "Ver detalhes da transação no Blockchair",
    "success_amount": "💰 Valor do Pagamento",
    "success_credit_title": "💰 Crédito Adicionado à Conta",
    "success_credit_desc": "foi adicionado com sucesso à sua conta.",
    "success_credit_balance": "Saldo atual:",
    "success_premium_title": "🎉 Benefícios Premium Ativados!",
    "success_premium_desc": "5× poder de voto, 💰 badge Ouro, sem anúncios, feed de membros",
    "success_notes_title": "📌 Notas Importantes:",
    "success_note_1": "• Este pagamento não é reembolsável",
    "success_note_2": "• Guarde o hash da transação como comprovante",
    "success_note_3": "• Compre a assinatura anual ($5/ano) na página da carteira",
    "success_note_4": "• Entre em contato com o suporte do oratio",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# ITALIAN (it) - fill remaining ~78 keys
# ============================================================
"it": {
    "nonrefundable_title": "Importante: Politica di Non Rimborso",
    "nonrefundable_desc": "Tutti i pagamenti in Bitcoin Cash sono <strong>non rimborsabili</strong>.",
    "nonrefundable_1": "• Verificare importo e indirizzo prima del pagamento",
    "nonrefundable_2": "• I depositi non sono rimborsabili per motivi di sicurezza",
    "nonrefundable_3": "• Procedere con il pagamento implica accettazione",
    "premium_title": "💎 Vantaggi Premium",
    "premium_price": "Abbonamento annuale — solo $5 USD/anno in BCH",
    "benefit_voting": "🗳️ <strong>5× Potere di Voto</strong>",
    "benefit_visibility": "📈 <strong>Visibilità Istantanea</strong>",
    "benefit_badge": "💰 <strong>Badge Oro</strong>",
    "benefit_adfree": "🚫 <strong>Senza Pubblicità</strong>",
    "benefit_feed": "⭐ <strong>Feed Esclusivo Membri</strong>",
    "generate_invoice_desc": "Solo per sviluppo e test.",
    "amount_label": "Importo (BCH)",
    "amount_min": "Importo minimo: 0.0001 BCH",
    "username_label": "Nome utente",
    "credit_info": "I crediti saranno aggiunti dopo il pagamento",
    "not_logged_in_warning": "⚠️ Non autenticato: Effettua prima il login su oratio.space",
    "no_login_warning": "Senza login nessun beneficio di pagamento",
    "generate_invoice_btn": "🚀 Genera Fattura",
    "footer_desc": "Pagamenti sicuri e trasparenti in criptovaluta",
    "help_title": "🛈 Aiuto Bitcoin Cash (Sii la tua banca)",
    "help_what_is_bch": "Cos'è Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) è una diramazione di Bitcoin che mantiene la visione originale del denaro elettronico peer-to-peer.",
    "help_install_wallet": "Installare un portafoglio",
    "help_install_wallet_desc": "Scarica un portafoglio Bitcoin Cash: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (desktop) o <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (mobile)",
    "help_getting_bch": "Ottenere Bitcoin Cash",
    "help_getting_bch_desc": "Puoi ottenere BCH tramite ATM o scambio privato.",
    "help_mixing": "Mescolare/privatizzare il tuo Bitcoin Cash",
    "help_mixing_desc_1": "Clicca col destro sul seguente simbolo:",
    "help_mixing_desc_2": "Imposta queste configurazioni per un mixing rapido:",
    "help_mixing_desc_3": "Usa solo output mescolati:",
    "invoice_nonrefundable_title": "Politica di Non Rimborso",
    "invoice_nonrefundable_desc": "Tutti i pagamenti non sono rimborsabili.",
    "invoice_membership_title": "Abbonamento annuale — $5 USD/anno",
    "invoice_membership_desc": "5× potere di voto, 💰 badge Oro, senza pubblicità, feed membri",
    "invoice_id_label": "📋 ID Fattura:",
    "invoice_amount_label": "💰 Importo del Pagamento:",
    "invoice_status_label": "📊 Stato:",
    "invoice_tx_label": "🔗 Transazione:",
    "invoice_send_to": "Invia esattamente <span style=\"color: #667eea;\">{{amount}} BCH</span> a questo indirizzo",
    "invoice_qr_title": "📱 Scansiona il QR per pagare",
    "invoice_check_btn": "🔍 Controlla Stato Pagamento",
    "invoice_check_again": "Controlla di nuovo",
    "invoice_check_failed": "Controllo fallito",
    "error_message_label": "Messaggio di Errore",
    "error_resolve_title": "Come risolvere",
    "error_resolve_1": "Aggiornare la pagina e riprovare",
    "error_resolve_2": "Attendere un momento e riprovare",
    "error_resolve_3": "Se il problema persiste, contattare il supporto",
    "error_resolve_4": "Verificare la connessione internet",
    "success_confirmed_desc": "Pagamento Bitcoin Cash confermato sulla blockchain",
    "success_invoice_id": "📋 ID Fattura",
    "success_tx_hash": "🔗 Hash della Transazione",
    "success_tx_view": "Vedi dettagli su Blockchair",
    "success_amount": "💰 Importo del Pagamento",
    "success_credit_desc": "è stato aggiunto al tuo account.",
    "success_credit_balance": "Saldo attuale:",
    "success_premium_desc": "5× potere di voto, 💰 badge Oro, senza pubblicità, feed membri",
    "success_notes_title": "📌 Note Importanti:",
    "success_note_1": "• Questo pagamento non è rimborsabile",
    "success_note_2": "• Conserva l'hash della transazione come ricevuta",
    "success_note_3": "• Acquista l'abbonamento annuale ($5/anno) dalla pagina portafoglio",
    "success_note_4": "• Contatta il supporto oratio per domande",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# DUTCH (nl) - fill remaining ~78 keys
# ============================================================
"nl": {
    "nonrefundable_title": "Belangrijk: Niet-restitueerbaar",
    "nonrefundable_desc": "Alle Bitcoin Cash-betalingen zijn <strong>niet restitueerbaar</strong>.",
    "nonrefundable_1": "• Controleer bedrag en adres vóór betaling",
    "nonrefundable_2": "• Stortingen zijn niet restitueerbaar",
    "nonrefundable_3": "• Betalen betekent akkoord met dit beleid",
    "premium_title": "💎 Premium Voordelen",
    "premium_price": "Jaarlidmaatschap — slechts $5 USD/jaar in BCH",
    "benefit_voting": "🗳️ <strong>5× Stemkracht</strong>",
    "benefit_visibility": "📈 <strong>Directe Zichtbaarheid</strong>",
    "benefit_badge": "💰 <strong>Gouden Badge</strong>",
    "benefit_adfree": "🚫 <strong>Reclamevrij</strong>",
    "benefit_feed": "⭐ <strong>Leden-Feed</strong>",
    "bch_help_btn": "🛈 BCH Bitcoin Cash Hulp",
    "return_home": "🏠 Terug naar oratio.space",
    "generate_invoice_title": "🎫 Factuur Genereren",
    "generate_invoice_desc": "Alleen voor ontwikkeling en testen.",
    "amount_label": "Bedrag (BCH)",
    "amount_min": "Minimumbedrag: 0.0001 BCH",
    "username_label": "Gebruikersnaam",
    "credit_info": "Credits worden na betaling bijgeschreven",
    "not_logged_in_warning": "⚠️ Niet ingelogd: Log eerst in op oratio.space",
    "no_login_warning": "Zonder login geen betalingsvoordelen",
    "footer_desc": "Veilige en transparante cryptocurrency betalingen",
    "help_title": "🛈 Bitcoin Cash Hulp (Wees je eigen bank)",
    "help_what_is_bch": "Wat is Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) is een afsplitsing van Bitcoin die de oorspronkelijke visie van peer-to-peer elektronisch geld bewaart.",
    "help_install_wallet": "Een wallet installeren",
    "help_install_wallet_desc": "Download een Bitcoin Cash wallet: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (desktop) of <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (mobiel)",
    "help_getting_bch": "Bitcoin Cash verkrijgen",
    "help_getting_bch_desc": "BCH is verkrijgbaar bij ATM's of via privéhandel.",
    "help_mixing": "Bitcoin Cash mixen/privatiseren",
    "help_mixing_desc_1": "Klik met rechts op het volgende symbool:",
    "help_mixing_desc_2": "Stel deze instellingen in voor snel mixen:",
    "help_mixing_desc_3": "Gebruik alleen gemixte uitgaven:",
    "invoice_nonrefundable_title": "Niet-restitueerbaar",
    "invoice_nonrefundable_desc": "Alle betalingen zijn niet restitueerbaar.",
    "invoice_membership_title": "Jaarlidmaatschap — $5 USD/jaar",
    "invoice_membership_desc": "5× stemkracht, 💰 gouden badge, reclamevrij, leden-feed",
    "invoice_payment_title": "💳 Bitcoin Cash Betaling",
    "invoice_id_label": "📋 Factuur-ID:",
    "invoice_amount_label": "💰 Betalingsbedrag:",
    "invoice_status_label": "📊 Status:",
    "invoice_tx_label": "🔗 Transactie:",
    "invoice_send_to": "Stuur precies <span style=\"color: #667eea;\">{{amount}} BCH</span> naar dit adres",
    "invoice_qr_title": "📱 Scan QR-code om te betalen",
    "invoice_check_btn": "🔍 Betalingsstatus Controleren",
    "invoice_check_again": "Opnieuw controleren",
    "invoice_check_failed": "Controle mislukt",
    "error_message_label": "Foutmelding",
    "error_resolve_title": "Hoe op te lossen",
    "error_resolve_1": "Pagina vernieuwen en opnieuw proberen",
    "error_resolve_2": "Even wachten en opnieuw proberen",
    "error_resolve_3": "Als het probleem aanhoudt, neem contact op met support",
    "error_resolve_4": "Controleer je internetverbinding",
    "success_confirmed_desc": "Bitcoin Cash betaling bevestigd op de blockchain",
    "success_invoice_id": "📋 Factuur-ID",
    "success_tx_hash": "🔗 Transactie-hash",
    "success_tx_view": "Bekijk transactiedetails op Blockchair",
    "success_amount": "💰 Betalingsbedrag",
    "success_credit_desc": "is toegevoegd aan je account.",
    "success_credit_balance": "Huidig saldo:",
    "success_premium_desc": "5× stemkracht, 💰 gouden badge, reclamevrij, leden-feed",
    "success_notes_title": "📌 Belangrijke Opmerkingen:",
    "success_note_1": "• Deze betaling is niet restitueerbaar",
    "success_note_2": "• Bewaar de transactie-hash als bewijs",
    "success_note_3": "• Koop het jaarlidmaatschap ($5/jaar) via je portemonnee",
    "success_note_4": "• Neem contact op met oratio-support bij vragen",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# POLISH (pl) - fill remaining ~78 keys
# ============================================================
"pl": {
    "nonrefundable_title": "Ważne: Brak Zwrotów",
    "nonrefundable_desc": "Wszystkie płatności Bitcoin Cash są <strong>bezzwrotne</strong>.",
    "nonrefundable_1": "• Sprawdź kwotę i adres przed płatnością",
    "nonrefundable_2": "• Wpłaty nie podlegają zwrotowi",
    "nonrefundable_3": "• Dokonanie płatności oznacza akceptację tej polityki",
    "premium_title": "💎 Korzyści Premium",
    "premium_price": "Roczne członkostwo — tylko $5 USD/rok w BCH",
    "benefit_voting": "🗳️ <strong>5× Siła Głosu</strong>",
    "benefit_visibility": "📈 <strong>Natychmiastowa Widoczność</strong>",
    "benefit_badge": "💰 <strong>Złota Odznaka</strong>",
    "benefit_adfree": "🚫 <strong>Bez Reklam</strong>",
    "benefit_feed": "⭐ <strong>Feed Członków</strong>",
    "bch_help_btn": "🛈 Pomoc BCH Bitcoin Cash",
    "return_home": "🏠 Wróć do oratio.space",
    "generate_invoice_title": "🎫 Wygeneruj Fakturę",
    "generate_invoice_desc": "Tylko do celów rozwojowych i testowych.",
    "amount_label": "Kwota (BCH)",
    "amount_min": "Minimalna kwota: 0.0001 BCH",
    "username_label": "Nazwa użytkownika",
    "credit_info": "Kredyty zostaną dodane po płatności",
    "not_logged_in_warning": "⚠️ Niezalogowany: Zaloguj się najpierw na oratio.space",
    "no_login_warning": "Bez logowania brak korzyści z płatności",
    "footer_desc": "Bezpieczne i przejrzyste płatności kryptowalutowe",
    "help_title": "🛈 Pomoc Bitcoin Cash (Bądź swoim bankiem)",
    "help_what_is_bch": "Czym jest Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) to odgałęzienie Bitcoina zachowujące oryginalną wizję elektronicznej gotówki peer-to-peer.",
    "help_install_wallet": "Instalacja portfela",
    "help_install_wallet_desc": "Pobierz portfel Bitcoin Cash: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (desktop) lub <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (mobilny)",
    "help_getting_bch": "Zdobywanie Bitcoin Cash",
    "help_getting_bch_desc": "BCH można zdobyć w bankomatach ATM lub przez prywatną wymianę.",
    "help_mixing": "Miksowanie/prywatyzacja Bitcoin Cash",
    "help_mixing_desc_1": "Kliknij prawym przyciskiem na następujący symbol:",
    "help_mixing_desc_2": "Ustaw te opcje dla szybkiego miksowania:",
    "help_mixing_desc_3": "Używaj tylko zmiksowanych wyników:",
    "invoice_nonrefundable_title": "Polityka Bezzwrotna",
    "invoice_nonrefundable_desc": "Wszystkie płatności są bezzwrotne.",
    "invoice_membership_title": "Roczne członkostwo — $5 USD/rok",
    "invoice_membership_desc": "5× siła głosu, 💰 złota odznaka, bez reklam, feed członków",
    "invoice_payment_title": "💳 Płatność Bitcoin Cash",
    "invoice_id_label": "📋 ID Faktury:",
    "invoice_amount_label": "💰 Kwota Płatności:",
    "invoice_status_label": "📊 Status:",
    "invoice_tx_label": "🔗 Transakcja:",
    "invoice_send_to": "Wyślij dokładnie <span style=\"color: #667eea;\">{{amount}} BCH</span> na ten adres",
    "invoice_qr_title": "📱 Zeskanuj QR aby zapłacić",
    "invoice_check_btn": "🔍 Sprawdź Status Płatności",
    "invoice_check_again": "Sprawdź ponownie",
    "invoice_check_failed": "Sprawdzanie nie powiodło się",
    "error_message_label": "Komunikat Błędu",
    "error_resolve_title": "Jak rozwiązać",
    "error_resolve_1": "Odśwież stronę i spróbuj ponownie",
    "error_resolve_2": "Poczekaj chwilę i spróbuj ponownie",
    "error_resolve_3": "Jeśli problem się utrzymuje, skontaktuj się z pomocą",
    "error_resolve_4": "Sprawdź połączenie internetowe",
    "success_confirmed_desc": "Płatność Bitcoin Cash potwierdzona w blockchain",
    "success_invoice_id": "📋 ID Faktury",
    "success_tx_hash": "🔗 Hash Transakcji",
    "success_tx_view": "Zobacz szczegóły transakcji na Blockchair",
    "success_amount": "💰 Kwota Płatności",
    "success_credit_desc": "został dodany do twojego konta.",
    "success_credit_balance": "Aktualny stan konta:",
    "success_premium_desc": "5× siła głosu, 💰 złota odznaka, bez reklam, feed członków",
    "success_notes_title": "📌 Ważne Uwagi:",
    "success_note_1": "• Ta płatność nie podlega zwrotowi",
    "success_note_2": "• Zachowaj hash transakcji jako dowód płatności",
    "success_note_3": "• Kup roczne członkostwo ($5/rok) na stronie portfela",
    "success_note_4": "• Skontaktuj się z pomocą oratio w razie pytań",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# SWEDISH (sv) - fill remaining ~90 keys
# ============================================================
"sv": {
    "nonrefundable_title": "Viktigt: Ej Återbetalningsbar",
    "nonrefundable_desc": "Alla Bitcoin Cash-betalningar är <strong>ej återbetalningsbara</strong>.",
    "nonrefundable_1": "• Verifiera belopp och adress före betalning",
    "nonrefundable_2": "• Insättningar är inte återbetalningsbara",
    "nonrefundable_3": "• Betalning innebär godkännande av denna policy",
    "premium_title": "💎 Premiumfördelar",
    "premium_price": "Årsmedlemskap — bara $5 USD/år i BCH",
    "benefit_voting": "🗳️ <strong>5× Röstkraft</strong>",
    "benefit_visibility": "📈 <strong>Direkt Synlighet</strong>",
    "benefit_badge": "💰 <strong>Guldmärke</strong>",
    "benefit_adfree": "🚫 <strong>Reklamfri</strong>",
    "benefit_feed": "⭐ <strong>Medlemsflöde</strong>",
    "bch_help_btn": "🛈 BCH Bitcoin Cash Hjälp",
    "generate_invoice_title": "🎫 Generera Betalningsfaktura",
    "generate_invoice_desc": "Endast för utveckling och test.",
    "amount_label": "Belopp (BCH)",
    "amount_min": "Minimibelopp: 0.0001 BCH",
    "username_label": "Användarnamn",
    "please_login": "Logga in först",
    "not_logged_in": "Ej inloggad",
    "logged_in_as": "✓ Inloggad som:",
    "credit_info": "Credits läggs till efter betalning",
    "not_logged_in_warning": "⚠️ Ej inloggad: Logga in på oratio.space först",
    "no_login_warning": "Utan inloggning inga betalningsfördelar",
    "generate_invoice_btn": "🚀 Generera Faktura",
    "login_required_btn": "🔒 Inloggning Krävs",
    "footer_desc": "Säkra och transparenta kryptovalutabetalningar",
    "help_title": "🛈 Bitcoin Cash Hjälp (Var din egen bank)",
    "help_what_is_bch": "Vad är Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) är en gren av Bitcoin som bevarar den ursprungliga visionen om elektroniska peer-to-peer-pengar.",
    "help_install_wallet": "Installera en plånbok",
    "help_install_wallet_desc": "Ladda ner en Bitcoin Cash-plånbok: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (dator) eller <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (mobil)",
    "help_getting_bch": "Skaffa Bitcoin Cash",
    "help_getting_bch_desc": "BCH kan fås via ATM eller privat handel.",
    "help_mixing": "Blanda/privatisera din Bitcoin Cash",
    "help_mixing_desc_1": "Högerklicka på följande symbol:",
    "help_mixing_desc_2": "Ställ in dessa inställningar:",
    "help_mixing_desc_3": "Använd bara blandade utgångar:",
    "payment_home_btn": "💳 Betalningstjänst",
    "go_to_oratio_btn": "🏠 Gå till oratio",
    "invoice_nonrefundable_title": "Ej Återbetalningsbar",
    "invoice_nonrefundable_desc": "Alla betalningar är ej återbetalningsbara.",
    "invoice_membership_title": "Årsmedlemskap — $5 USD/år",
    "invoice_membership_desc": "5× röstkraft, 💰 guldmärke, reklamfri, medlemsflöde",
    "invoice_payment_title": "💳 Bitcoin Cash Betalning",
    "invoice_id_label": "📋 Faktura-ID:",
    "invoice_amount_label": "💰 Betalningsbelopp:",
    "invoice_status_label": "📊 Status:",
    "invoice_tx_label": "🔗 Transaktion:",
    "invoice_send_to": "Skicka exakt <span style=\"color: #667eea;\">{{amount}} BCH</span> till denna adress",
    "invoice_copy_btn": "📋 Kopiera",
    "invoice_qr_title": "📱 Skanna QR-kod för att betala",
    "invoice_check_btn": "🔍 Kontrollera Status",
    "invoice_back_btn": "🏠 Tillbaka",
    "invoice_checking": "Kontrollerar...",
    "invoice_check_again": "Kontrollera igen",
    "invoice_check_failed": "Kontroll misslyckades",
    "invoice_address_copied": "Adress kopierad",
    "error_title": "Något gick fel!",
    "error_message_label": "Felmeddelande",
    "error_resolve_title": "Hur löser man det",
    "error_resolve_1": "Uppdatera sidan och försök igen",
    "error_resolve_2": "Vänta en stund och försök igen",
    "error_resolve_3": "Om problemet kvarstår, kontakta support",
    "error_resolve_4": "Kontrollera din internetanslutning",
    "success_title": "Betalning Slutförd!",
    "success_confirmed_title": "Betalning Bekräftad",
    "success_confirmed_desc": "Bitcoin Cash-betalning bekräftad i blockkedjan",
    "success_invoice_id": "📋 Faktura-ID",
    "success_tx_hash": "🔗 Transaktionshash",
    "success_tx_view": "Visa transaktionsdetaljer på Blockchair",
    "success_amount": "💰 Betalningsbelopp",
    "success_credit_title": "💰 Kredit Tillagd",
    "success_credit_desc": "har lagts till på ditt konto.",
    "success_credit_balance": "Aktuellt saldo:",
    "success_premium_title": "🎉 Premiumfördelar Aktiverade!",
    "success_premium_desc": "5× röstkraft, 💰 guldmärke, reklamfri, medlemsflöde",
    "success_notes_title": "📌 Viktig Information:",
    "success_note_1": "• Denna betalning är inte återbetalningsbar",
    "success_note_2": "• Spara transaktionshashen som bevis",
    "success_note_3": "• Köp årsmedlemskap ($5/år) via plånbokssidan",
    "success_note_4": "• Kontakta oratio-support vid frågor",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# TRADITIONAL CHINESE (zh_Hant) - fill remaining ~90 keys
# ============================================================
"zh_Hant": {
    "bch_payment_service": "💳 Bitcoin Cash 支付服務",
    "nonrefundable_title": "重要：不退款政策",
    "nonrefundable_desc": "所有 Bitcoin Cash 支付<strong>不可退款</strong>。",
    "nonrefundable_1": "• 請在付款前確認金額和地址",
    "nonrefundable_2": "• 基於安全原因，存款不可退還",
    "nonrefundable_3": "• 進行付款即表示同意此政策",
    "premium_title": "💎 高級會員特權",
    "premium_price": "年度會員 — 僅需 $5 USD/年（BCH 支付）",
    "benefit_voting": "🗳️ <strong>5倍投票權</strong>",
    "benefit_visibility": "📈 <strong>即時可見性</strong>",
    "benefit_badge": "💰 <strong>金牌徽章</strong>",
    "benefit_adfree": "🚫 <strong>無廣告體驗</strong>",
    "benefit_feed": "⭐ <strong>會員專屬動態</strong>",
    "bch_help_btn": "🛈 BCH Bitcoin Cash 幫助",
    "generate_invoice_title": "🎫 產生付款發票",
    "generate_invoice_desc": "僅供開發測試使用。",
    "amount_label": "金額 (BCH)",
    "amount_min": "最低金額：0.0001 BCH",
    "username_label": "使用者名稱",
    "please_login": "請先登入",
    "not_logged_in": "未登入",
    "logged_in_as": "✓ 已登入為：",
    "credit_info": "付款後積分將添加到您的帳戶",
    "not_logged_in_warning": "⚠️ 未登入：請先登入 oratio.space",
    "no_login_warning": "未登入無法獲得付款福利",
    "generate_invoice_btn": "🚀 產生發票",
    "login_required_btn": "🔒 需要登入",
    "footer_desc": "提供安全透明的加密貨幣支付",
    "help_title": "🛈 Bitcoin Cash 幫助（做自己的銀行）",
    "help_what_is_bch": "什麼是 Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) 是比特幣的分支，保留了點對點電子現金的原始願景。",
    "help_install_wallet": "安裝錢包",
    "help_install_wallet_desc": "下載 Bitcoin Cash 錢包：<a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a>（桌面版）或 <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a>（手機版）",
    "help_getting_bch": "取得 Bitcoin Cash",
    "help_getting_bch_desc": "可透過 ATM 或私人交易取得 BCH。",
    "help_mixing": "混幣/隱私保護",
    "help_mixing_desc_1": "右鍵點擊以下符號：",
    "help_mixing_desc_2": "設定這些選項以實現快速混幣：",
    "help_mixing_desc_3": "僅使用混合後的輸出：",
    "payment_home_btn": "💳 支付服務首頁",
    "go_to_oratio_btn": "🏠 前往 oratio",
    "invoice_nonrefundable_title": "不退款政策",
    "invoice_nonrefundable_desc": "所有付款不可退款。",
    "invoice_membership_title": "年度會員 — $5 USD/年",
    "invoice_membership_desc": "5倍投票權、💰 金牌徽章、無廣告、會員專屬動態",
    "invoice_payment_title": "💳 Bitcoin Cash 支付",
    "invoice_id_label": "📋 發票 ID：",
    "invoice_amount_label": "💰 付款金額：",
    "invoice_status_label": "📊 狀態：",
    "invoice_tx_label": "🔗 交易：",
    "invoice_send_to": "請將 <span style=\"color: #667eea;\">{{amount}} BCH</span> 發送到以下地址",
    "invoice_copy_btn": "📋 複製",
    "invoice_qr_title": "📱 掃描 QR 碼付款",
    "invoice_check_btn": "🔍 檢查付款狀態",
    "invoice_back_btn": "🏠 返回",
    "invoice_checking": "檢查中...",
    "invoice_check_again": "再次檢查",
    "invoice_check_failed": "檢查失敗",
    "invoice_address_copied": "地址已複製",
    "error_title": "出了點問題！",
    "error_message_label": "錯誤訊息",
    "error_resolve_title": "解決方法",
    "error_resolve_1": "重新整理頁面再試一次",
    "error_resolve_2": "稍等片刻後重試",
    "error_resolve_3": "如問題持續，請聯絡客服",
    "error_resolve_4": "檢查網路連線",
    "success_title": "付款成功完成！",
    "success_confirmed_title": "付款已確認",
    "success_confirmed_desc": "Bitcoin Cash 付款已在區塊鏈上確認",
    "success_invoice_id": "📋 發票 ID",
    "success_tx_hash": "🔗 交易雜湊",
    "success_tx_view": "在 Blockchair 查看交易詳情",
    "success_amount": "💰 付款金額",
    "success_credit_title": "💰 帳戶積分已添加",
    "success_credit_desc": "已成功添加到您的帳戶。",
    "success_credit_balance": "目前積分餘額：",
    "success_premium_title": "🎉 高級會員已啟用！",
    "success_premium_desc": "5倍投票權、💰 金牌徽章、無廣告、會員專屬動態",
    "success_notes_title": "📌 重要提示：",
    "success_note_1": "• 此付款不可退款",
    "success_note_2": "• 請保存交易雜湊作為付款憑證",
    "success_note_3": "• 在錢包頁面購買年度會員（$5/年）",
    "success_note_4": "• 如有問題請聯絡 oratio 客服",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# ARABIC (ar) - fill remaining ~96 keys
# ============================================================
"ar": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 خدمة الدفع بيتكوين كاش",
    "nonrefundable_title": "مهم: سياسة عدم الاسترداد",
    "nonrefundable_desc": "جميع مدفوعات Bitcoin Cash <strong>غير قابلة للاسترداد</strong>.",
    "nonrefundable_1": "• يرجى التحقق من المبلغ والعنوان قبل الدفع",
    "nonrefundable_2": "• الإيداعات غير قابلة للاسترداد لأسباب أمنية",
    "nonrefundable_3": "• المتابعة بالدفع تعني الموافقة على هذه السياسة",
    "premium_title": "💎 مزايا بريميوم",
    "premium_price": "اشتراك سنوي — فقط $5 USD/سنة بـ BCH",
    "benefit_voting": "🗳️ <strong>5× قوة التصويت</strong>",
    "benefit_visibility": "📈 <strong>ظهور فوري</strong>",
    "benefit_badge": "💰 <strong>شارة ذهبية</strong>",
    "benefit_adfree": "🚫 <strong>بدون إعلانات</strong>",
    "benefit_feed": "⭐ <strong>خلاصة حصرية للأعضاء</strong>",
    "bch_help_btn": "🛈 مساعدة BCH Bitcoin Cash",
    "return_home": "🏠 العودة إلى oratio.space",
    "generate_invoice_title": "🎫 إنشاء فاتورة دفع",
    "generate_invoice_desc": "للتطوير والاختبار فقط.",
    "amount_label": "المبلغ (BCH)",
    "amount_min": "الحد الأدنى: 0.0001 BCH",
    "username_label": "اسم المستخدم",
    "please_login": "يرجى تسجيل الدخول أولاً",
    "not_logged_in": "غير مسجل الدخول",
    "logged_in_as": "✓ مسجل الدخول باسم:",
    "credit_info": "ستُضاف الأرصدة بعد الدفع",
    "not_logged_in_warning": "⚠️ غير مسجل: يرجى تسجيل الدخول إلى oratio.space أولاً",
    "no_login_warning": "بدون تسجيل الدخول لا توجد مزايا دفع",
    "generate_invoice_btn": "🚀 إنشاء الفاتورة",
    "login_required_btn": "🔒 تسجيل الدخول مطلوب",
    "footer_copyright": "© 2026 oratio - نظام الدفع بيتكوين كاش",
    "footer_desc": "مدفوعات آمنة وشفافة بالعملات المشفرة",
    "help_title": "🛈 مساعدة Bitcoin Cash (كن بنكك الخاص)",
    "help_what_is_bch": "ما هو Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) هو فرع من Bitcoin يحتفظ بالرؤية الأصلية للنقود الإلكترونية بين الأقران.",
    "help_install_wallet": "تثبيت محفظة",
    "help_install_wallet_desc": "حمّل محفظة Bitcoin Cash: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (حاسوب) أو <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (جوال)",
    "help_getting_bch": "الحصول على Bitcoin Cash",
    "help_getting_bch_desc": "يمكنك الحصول على BCH من أجهزة الصراف الآلي أو التبادل الخاص.",
    "help_mixing": "خلط/تخصيص Bitcoin Cash",
    "help_mixing_desc_1": "انقر بالزر الأيمن على الرمز التالي:",
    "help_mixing_desc_2": "اضبط هذه الإعدادات للخلط السريع:",
    "help_mixing_desc_3": "استخدم فقط المخرجات المخلوطة:",
    "payment_home_btn": "💳 خدمة الدفع",
    "go_to_oratio_btn": "🏠 انتقل إلى oratio",
    "invoice_nonrefundable_title": "سياسة عدم الاسترداد",
    "invoice_nonrefundable_desc": "جميع المدفوعات غير قابلة للاسترداد.",
    "invoice_membership_title": "اشتراك سنوي — $5 USD/سنة",
    "invoice_membership_desc": "5× قوة تصويت، 💰 شارة ذهبية، بدون إعلانات، خلاصة أعضاء",
    "invoice_payment_title": "💳 دفع Bitcoin Cash",
    "invoice_id_label": "📋 رقم الفاتورة:",
    "invoice_amount_label": "💰 مبلغ الدفع:",
    "invoice_status_label": "📊 الحالة:",
    "invoice_tx_label": "🔗 المعاملة:",
    "invoice_send_to": "أرسل بالضبط <span style=\"color: #667eea;\">{{amount}} BCH</span> إلى هذا العنوان",
    "invoice_copy_btn": "📋 نسخ",
    "invoice_qr_title": "📱 امسح رمز QR للدفع",
    "invoice_check_btn": "🔍 التحقق من حالة الدفع",
    "invoice_back_btn": "🏠 رجوع",
    "invoice_checking": "جاري التحقق...",
    "invoice_check_again": "تحقق مرة أخرى",
    "invoice_check_failed": "فشل التحقق",
    "invoice_address_copied": "تم نسخ العنوان",
    "error_title": "حدث خطأ ما!",
    "error_message_label": "رسالة الخطأ",
    "error_resolve_title": "كيفية الحل",
    "error_resolve_1": "أعد تحميل الصفحة وحاول مرة أخرى",
    "error_resolve_2": "انتظر قليلاً وحاول مرة أخرى",
    "error_resolve_3": "إذا استمرت المشكلة، اتصل بالدعم",
    "error_resolve_4": "تحقق من اتصال الإنترنت",
    "success_title": "تم الدفع بنجاح!",
    "success_confirmed_title": "تم تأكيد الدفع",
    "success_confirmed_desc": "تم تأكيد دفع Bitcoin Cash على البلوكتشين",
    "success_invoice_id": "📋 رقم الفاتورة",
    "success_tx_hash": "🔗 هاش المعاملة",
    "success_tx_view": "عرض تفاصيل المعاملة على Blockchair",
    "success_amount": "💰 مبلغ الدفع",
    "success_credit_title": "💰 تمت إضافة الرصيد",
    "success_credit_desc": "تمت إضافته بنجاح إلى حسابك.",
    "success_credit_balance": "الرصيد الحالي:",
    "success_premium_title": "🎉 تم تفعيل المزايا المميزة!",
    "success_premium_desc": "5× قوة تصويت، 💰 شارة ذهبية، بدون إعلانات، خلاصة أعضاء",
    "success_notes_title": "📌 ملاحظات مهمة:",
    "success_note_1": "• هذا الدفع غير قابل للاسترداد",
    "success_note_2": "• احتفظ بهاش المعاملة كإثبات",
    "success_note_3": "• اشترِ الاشتراك السنوي ($5/سنة) من صفحة المحفظة",
    "success_note_4": "• تواصل مع دعم oratio للاستفسارات",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# DANISH (da) - full
# ============================================================
"da": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Bitcoin Cash Betalingstjeneste",
    "nonrefundable_title": "Vigtigt: Ikke Refunderbar",
    "nonrefundable_desc": "Alle Bitcoin Cash-betalinger er <strong>ikke refunderbare</strong>.",
    "nonrefundable_1": "• Kontroller beløb og adresse før betaling",
    "nonrefundable_2": "• Indbetalinger kan ikke refunderes",
    "nonrefundable_3": "• Betaling betyder accept af denne politik",
    "premium_title": "💎 Premium Fordele",
    "premium_price": "Årsmedlemskab — kun $5 USD/år i BCH",
    "benefit_voting": "🗳️ <strong>5× Stemmekraft</strong>",
    "benefit_visibility": "📈 <strong>Øjeblikkelig Synlighed</strong>",
    "benefit_badge": "💰 <strong>Guldmærke</strong>",
    "benefit_adfree": "🚫 <strong>Reklamefri</strong>",
    "benefit_feed": "⭐ <strong>Medlemsfeed</strong>",
    "bch_help_btn": "🛈 BCH Bitcoin Cash Hjælp",
    "return_home": "🏠 Tilbage til oratio.space",
    "generate_invoice_title": "🎫 Generer Betalingsfaktura",
    "generate_invoice_desc": "Kun til udvikling og test.",
    "amount_label": "Beløb (BCH)",
    "amount_min": "Minimumsbeløb: 0.0001 BCH",
    "username_label": "Brugernavn",
    "please_login": "Log ind først",
    "not_logged_in": "Ikke logget ind",
    "logged_in_as": "✓ Logget ind som:",
    "credit_info": "Credits tilføjes efter betaling",
    "not_logged_in_warning": "⚠️ Ikke logget ind: Log ind på oratio.space først",
    "no_login_warning": "Uden login ingen betalingsfordele",
    "generate_invoice_btn": "🚀 Generer Faktura",
    "login_required_btn": "🔒 Login Påkrævet",
    "footer_copyright": "© 2026 oratio - Bitcoin Cash Betalingssystem",
    "footer_desc": "Sikre og gennemsigtige kryptovaluta-betalinger",
    "help_title": "🛈 Bitcoin Cash Hjælp (Vær din egen bank)",
    "help_what_is_bch": "Hvad er Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) er en gren af Bitcoin der bevarer den originale vision om peer-to-peer elektroniske penge.",
    "help_install_wallet": "Installation af tegnebog",
    "help_install_wallet_desc": "Download en Bitcoin Cash tegnebog: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (desktop) eller <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (mobil)",
    "help_getting_bch": "Anskaffelse af Bitcoin Cash",
    "help_getting_bch_desc": "BCH kan fås via ATM eller privat handel.",
    "help_mixing": "Blanding/privatisering af Bitcoin Cash",
    "help_mixing_desc_1": "Højreklik på følgende symbol:",
    "help_mixing_desc_2": "Indstil disse for hurtig blanding:",
    "help_mixing_desc_3": "Brug kun blandede udgange:",
    "payment_home_btn": "💳 Betalingstjeneste",
    "go_to_oratio_btn": "🏠 Gå til oratio",
    "invoice_nonrefundable_title": "Ikke Refunderbar",
    "invoice_nonrefundable_desc": "Alle betalinger er ikke refunderbare.",
    "invoice_membership_title": "Årsmedlemskab — $5 USD/år",
    "invoice_membership_desc": "5× stemmekraft, 💰 guldmærke, reklamefri, medlemsfeed",
    "invoice_payment_title": "💳 Bitcoin Cash Betaling",
    "invoice_id_label": "📋 Faktura-ID:",
    "invoice_amount_label": "💰 Betalingsbeløb:",
    "invoice_status_label": "📊 Status:",
    "invoice_tx_label": "🔗 Transaktion:",
    "invoice_send_to": "Send nøjagtigt <span style=\"color: #667eea;\">{{amount}} BCH</span> til denne adresse",
    "invoice_copy_btn": "📋 Kopier",
    "invoice_qr_title": "📱 Scan QR-kode for at betale",
    "invoice_check_btn": "🔍 Kontroller Status",
    "invoice_back_btn": "🏠 Tilbage",
    "invoice_checking": "Kontrollerer...",
    "invoice_check_again": "Kontroller igen",
    "invoice_check_failed": "Kontrol fejlede",
    "invoice_address_copied": "Adresse kopieret",
    "error_title": "Noget gik galt!",
    "error_message_label": "Fejlmeddelelse",
    "error_resolve_title": "Sådan løser du det",
    "error_resolve_1": "Genindlæs siden og prøv igen",
    "error_resolve_2": "Vent lidt og prøv igen",
    "error_resolve_3": "Hvis problemet fortsætter, kontakt support",
    "error_resolve_4": "Kontroller din internetforbindelse",
    "success_title": "Betaling Gennemført!",
    "success_confirmed_title": "Betaling Bekræftet",
    "success_confirmed_desc": "Bitcoin Cash betaling bekræftet på blockchain",
    "success_invoice_id": "📋 Faktura-ID",
    "success_tx_hash": "🔗 Transaktionshash",
    "success_tx_view": "Se transaktionsdetaljer på Blockchair",
    "success_amount": "💰 Betalingsbeløb",
    "success_credit_title": "💰 Kredit Tilføjet",
    "success_credit_desc": "er blevet tilføjet til din konto.",
    "success_credit_balance": "Nuværende saldo:",
    "success_premium_title": "🎉 Premium Fordele Aktiveret!",
    "success_premium_desc": "5× stemmekraft, 💰 guldmærke, reklamefri, medlemsfeed",
    "success_notes_title": "📌 Vigtig Information:",
    "success_note_1": "• Denne betaling kan ikke refunderes",
    "success_note_2": "• Gem transaktionshashen som bevis",
    "success_note_3": "• Køb årsmedlemskab ($5/år) fra din tegnebog",
    "success_note_4": "• Kontakt oratio-support ved spørgsmål",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# FINNISH (fi) - full
# ============================================================
"fi": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Bitcoin Cash Maksupalvelu",
    "nonrefundable_title": "Tärkeää: Ei Palautettavissa",
    "nonrefundable_desc": "Kaikki Bitcoin Cash -maksut ovat <strong>palautuskelvottomia</strong>.",
    "nonrefundable_1": "• Tarkista summa ja osoite ennen maksua",
    "nonrefundable_2": "• Talletuksia ei palauteta turvallisuussyistä",
    "nonrefundable_3": "• Maksaminen tarkoittaa tämän käytännön hyväksymistä",
    "premium_title": "💎 Premium-edut",
    "premium_price": "Vuosijäsenyys — vain $5 USD/vuosi BCH:llä",
    "benefit_voting": "🗳️ <strong>5× Äänivalta</strong>",
    "benefit_visibility": "📈 <strong>Välitön Näkyvyys</strong>",
    "benefit_badge": "💰 <strong>Kultamerkki</strong>",
    "benefit_adfree": "🚫 <strong>Mainokseton</strong>",
    "benefit_feed": "⭐ <strong>Jäsenten Syöte</strong>",
    "bch_help_btn": "🛈 BCH Bitcoin Cash Ohje",
    "return_home": "🏠 Takaisin oratio.space:iin",
    "generate_invoice_title": "🎫 Luo Maksulasku",
    "generate_invoice_desc": "Vain kehitys- ja testikäyttöön.",
    "amount_label": "Summa (BCH)",
    "amount_min": "Vähimmäissumma: 0.0001 BCH",
    "username_label": "Käyttäjänimi",
    "please_login": "Kirjaudu ensin",
    "not_logged_in": "Ei kirjautunut",
    "logged_in_as": "✓ Kirjautunut:",
    "credit_info": "Luotot lisätään maksun jälkeen",
    "not_logged_in_warning": "⚠️ Ei kirjautunut: Kirjaudu ensin oratio.space:iin",
    "no_login_warning": "Ilman kirjautumista ei maksuetuuksia",
    "generate_invoice_btn": "🚀 Luo Lasku",
    "login_required_btn": "🔒 Kirjautuminen Vaaditaan",
    "footer_copyright": "© 2026 oratio - Bitcoin Cash Maksujärjestelmä",
    "footer_desc": "Turvallisia ja läpinäkyviä kryptovaluuttamaksuja",
    "help_title": "🛈 Bitcoin Cash Ohje (Ole oma pankkisi)",
    "help_what_is_bch": "Mikä on Bitcoin Cash",
    "help_what_is_bch_desc": "Bitcoin Cash (BCH) on Bitcoinin haara, joka säilyttää alkuperäisen vertaisverkon elektronisen rahan vision.",
    "help_install_wallet": "Lompakon asennus",
    "help_install_wallet_desc": "Lataa Bitcoin Cash -lompakko: <a href=\"https://electroncash.org\" target=\"_blank\">Electron Cash</a> (tietokone) tai <a href=\"https://wallet.bitcoin.com\" target=\"_blank\">Bitcoin.com Wallet</a> (mobiili)",
    "help_getting_bch": "Bitcoin Cashin hankkiminen",
    "help_getting_bch_desc": "BCH:ta saa automaateista tai yksityiskaupalla.",
    "help_mixing": "Bitcoin Cashin sekoitus/yksityistäminen",
    "help_mixing_desc_1": "Napsauta seuraavaa symbolia hiiren oikealla:",
    "help_mixing_desc_2": "Aseta nämä asetukset nopeaa sekoitusta varten:",
    "help_mixing_desc_3": "Käytä vain sekoitettuja tulosteita:",
    "payment_home_btn": "💳 Maksupalvelu",
    "go_to_oratio_btn": "🏠 Siirry oratioon",
    "invoice_nonrefundable_title": "Ei Palautettavissa",
    "invoice_nonrefundable_desc": "Kaikkia maksuja ei palauteta.",
    "invoice_membership_title": "Vuosijäsenyys — $5 USD/vuosi",
    "invoice_membership_desc": "5× äänivalta, 💰 kultamerkki, mainokseton, jäsenten syöte",
    "invoice_payment_title": "💳 Bitcoin Cash Maksu",
    "invoice_id_label": "📋 Lasku-ID:",
    "invoice_amount_label": "💰 Maksusumma:",
    "invoice_status_label": "📊 Tila:",
    "invoice_tx_label": "🔗 Tapahtuma:",
    "invoice_send_to": "Lähetä tasan <span style=\"color: #667eea;\">{{amount}} BCH</span> tähän osoitteeseen",
    "invoice_copy_btn": "📋 Kopioi",
    "invoice_qr_title": "📱 Skannaa QR-koodi maksaaksesi",
    "invoice_check_btn": "🔍 Tarkista Tila",
    "invoice_back_btn": "🏠 Takaisin",
    "invoice_checking": "Tarkistetaan...",
    "invoice_check_again": "Tarkista uudelleen",
    "invoice_check_failed": "Tarkistus epäonnistui",
    "invoice_address_copied": "Osoite kopioitu",
    "error_title": "Jotain meni pieleen!",
    "error_message_label": "Virheilmoitus",
    "error_resolve_title": "Ratkaisuehdotukset",
    "error_resolve_1": "Päivitä sivu ja yritä uudelleen",
    "error_resolve_2": "Odota hetki ja yritä uudelleen",
    "error_resolve_3": "Jos ongelma jatkuu, ota yhteyttä tukeen",
    "error_resolve_4": "Tarkista internetyhteytesi",
    "success_title": "Maksu Suoritettu!",
    "success_confirmed_title": "Maksu Vahvistettu",
    "success_confirmed_desc": "Bitcoin Cash -maksu vahvistettu lohkoketjussa",
    "success_invoice_id": "📋 Lasku-ID",
    "success_tx_hash": "🔗 Tapahtumatiiviste",
    "success_tx_view": "Katso tapahtumatiedot Blockchairissa",
    "success_amount": "💰 Maksusumma",
    "success_credit_title": "💰 Luotto Lisätty",
    "success_credit_desc": "on lisätty tilillesi.",
    "success_credit_balance": "Nykyinen saldo:",
    "success_premium_title": "🎉 Premium-edut Aktivoitu!",
    "success_premium_desc": "5× äänivalta, 💰 kultamerkki, mainokseton, jäsenten syöte",
    "success_notes_title": "📌 Tärkeää:",
    "success_note_1": "• Tätä maksua ei palauteta",
    "success_note_2": "• Tallenna tapahtumatunnus todisteeksi",
    "success_note_3": "• Osta vuosijäsenyys ($5/vuosi) lompakkosivultasi",
    "success_note_4": "• Ota yhteyttä oratio-tukeen kysymyksissä",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# PERSIAN (fa) - core keys
# ============================================================
"fa": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 سرویس پرداخت بیتکوین کش",
    "nonrefundable_title": "مهم: سیاست عدم بازپرداخت",
    "return_home": "🏠 بازگشت به oratio.space",
    "please_login": "لطفاً ابتدا وارد شوید",
    "not_logged_in": "وارد نشده‌اید",
    "logged_in_as": "✓ وارد شده به عنوان:",
    "generate_invoice_btn": "🚀 ایجاد فاکتور",
    "login_required_btn": "🔒 ورود لازم است",
    "footer_copyright": "© 2026 oratio - سیستم پرداخت بیتکوین کش",
    "payment_home_btn": "💳 سرویس پرداخت",
    "go_to_oratio_btn": "🏠 رفتن به oratio",
    "invoice_copy_btn": "📋 کپی",
    "invoice_check_btn": "🔍 بررسی وضعیت",
    "invoice_back_btn": "🏠 بازگشت",
    "invoice_checking": "در حال بررسی...",
    "invoice_address_copied": "آدرس کپی شد",
    "error_title": "مشکلی پیش آمد!",
    "success_title": "پرداخت با موفقیت انجام شد!",
    "success_confirmed_title": "پرداخت تأیید شد",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# VIETNAMESE (vi) - core keys
# ============================================================
"vi": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Dịch Vụ Thanh Toán Bitcoin Cash",
    "nonrefundable_title": "Quan trọng: Không Hoàn Tiền",
    "return_home": "🏠 Quay lại oratio.space",
    "please_login": "Vui lòng đăng nhập trước",
    "not_logged_in": "Chưa đăng nhập",
    "logged_in_as": "✓ Đã đăng nhập:",
    "generate_invoice_btn": "🚀 Tạo Hóa Đơn",
    "login_required_btn": "🔒 Cần Đăng Nhập",
    "footer_copyright": "© 2026 oratio - Hệ Thống Thanh Toán Bitcoin Cash",
    "payment_home_btn": "💳 Dịch Vụ Thanh Toán",
    "go_to_oratio_btn": "🏠 Đến oratio",
    "invoice_copy_btn": "📋 Sao chép",
    "invoice_check_btn": "🔍 Kiểm Tra Trạng Thái",
    "invoice_back_btn": "🏠 Quay lại",
    "invoice_checking": "Đang kiểm tra...",
    "invoice_address_copied": "Đã sao chép địa chỉ",
    "error_title": "Đã xảy ra lỗi!",
    "success_title": "Thanh Toán Thành Công!",
    "success_confirmed_title": "Thanh Toán Đã Xác Nhận",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# INDONESIAN (id) - core keys
# ============================================================
"id": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Layanan Pembayaran Bitcoin Cash",
    "nonrefundable_title": "Penting: Tidak Dapat Dikembalikan",
    "return_home": "🏠 Kembali ke oratio.space",
    "please_login": "Silakan login dulu",
    "not_logged_in": "Belum login",
    "logged_in_as": "✓ Login sebagai:",
    "generate_invoice_btn": "🚀 Buat Invoice",
    "login_required_btn": "🔒 Login Diperlukan",
    "footer_copyright": "© 2026 oratio - Sistem Pembayaran Bitcoin Cash",
    "payment_home_btn": "💳 Layanan Pembayaran",
    "go_to_oratio_btn": "🏠 Ke oratio",
    "invoice_copy_btn": "📋 Salin",
    "invoice_check_btn": "🔍 Cek Status",
    "invoice_back_btn": "🏠 Kembali",
    "invoice_checking": "Memeriksa...",
    "invoice_address_copied": "Alamat disalin",
    "error_title": "Terjadi Kesalahan!",
    "success_title": "Pembayaran Berhasil!",
    "success_confirmed_title": "Pembayaran Dikonfirmasi",
    "about_contact": "oratio1809@proton.me",
},

# ============================================================
# GREEK (el) - core keys
# ============================================================
"el": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Υπηρεσία Πληρωμής Bitcoin Cash",
    "return_home": "🏠 Επιστροφή στο oratio.space",
    "please_login": "Συνδεθείτε πρώτα",
    "not_logged_in": "Μη συνδεδεμένος",
    "invoice_copy_btn": "📋 Αντιγραφή",
    "invoice_check_btn": "🔍 Έλεγχος Κατάστασης",
    "invoice_back_btn": "🏠 Πίσω",
    "error_title": "Κάτι πήγε στραβά!",
    "success_title": "Η Πληρωμή Ολοκληρώθηκε!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Σύστημα Πληρωμών Bitcoin Cash",
},

# ============================================================
# CZECH (cs) - core keys
# ============================================================
"cs": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Platební Služba Bitcoin Cash",
    "return_home": "🏠 Zpět na oratio.space",
    "please_login": "Nejprve se přihlaste",
    "not_logged_in": "Nepřihlášen",
    "invoice_copy_btn": "📋 Kopírovat",
    "invoice_check_btn": "🔍 Zkontrolovat Stav",
    "invoice_back_btn": "🏠 Zpět",
    "error_title": "Něco se pokazilo!",
    "success_title": "Platba Úspěšná!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Platební Systém Bitcoin Cash",
},

# ============================================================
# BULGARIAN (bg) - core keys
# ============================================================
"bg": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Услуга за Плащане Bitcoin Cash",
    "return_home": "🏠 Обратно към oratio.space",
    "please_login": "Моля, влезте първо",
    "invoice_copy_btn": "📋 Копиране",
    "invoice_check_btn": "🔍 Проверка на Статус",
    "invoice_back_btn": "🏠 Назад",
    "error_title": "Нещо се обърка!",
    "success_title": "Плащането е Успешно!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Платежна Система Bitcoin Cash",
},

# ============================================================
# CROATIAN (hr) - core keys
# ============================================================
"hr": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Bitcoin Cash Platni Servis",
    "return_home": "🏠 Natrag na oratio.space",
    "please_login": "Prvo se prijavite",
    "invoice_copy_btn": "📋 Kopiraj",
    "invoice_check_btn": "🔍 Provjeri Status",
    "invoice_back_btn": "🏠 Natrag",
    "error_title": "Nešto je pošlo po zlu!",
    "success_title": "Plaćanje Uspješno!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Bitcoin Cash Platni Sustav",
},

# ============================================================
# CATALAN (ca) - core keys
# ============================================================
"ca": {
    "site_title": "✨ oratio",
    "bch_payment_service": "💳 Servei de Pagament Bitcoin Cash",
    "return_home": "🏠 Tornar a oratio.space",
    "please_login": "Inicieu sessió primer",
    "invoice_copy_btn": "📋 Copiar",
    "invoice_check_btn": "🔍 Comprovar Estat",
    "invoice_back_btn": "🏠 Enrere",
    "error_title": "Alguna cosa ha anat malament!",
    "success_title": "Pagament Completat!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Sistema de Pagament Bitcoin Cash",
},

# ============================================================
# BASQUE (eu) - core keys
# ============================================================
"eu": {
    "site_title": "✨ oratio",
    "return_home": "🏠 Itzuli oratio.space-ra",
    "invoice_copy_btn": "📋 Kopiatu",
    "invoice_back_btn": "🏠 Atzera",
    "error_title": "Zerbait gaizki joan da!",
    "success_title": "Ordainketa Osatua!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Bitcoin Cash Ordainketa Sistema",
},

# ============================================================
# ESPERANTO (eo) - core keys
# ============================================================
"eo": {
    "site_title": "✨ oratio",
    "return_home": "🏠 Reveni al oratio.space",
    "invoice_copy_btn": "📋 Kopii",
    "invoice_back_btn": "🏠 Reen",
    "error_title": "Io misfunkciis!",
    "success_title": "Pago Sukcesis!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Bitcoin Cash Pagsistemo",
},

# ============================================================
# IRISH (ga) - core keys
# ============================================================
"ga": {
    "site_title": "✨ oratio",
    "return_home": "🏠 Ar ais go oratio.space",
    "invoice_copy_btn": "📋 Cóipeáil",
    "invoice_back_btn": "🏠 Ar ais",
    "error_title": "Chuaigh rud éigin mícheart!",
    "success_title": "Íocaíocht Críochnaithe!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Córas Íocaíochta Bitcoin Cash",
},

# ============================================================
# GALICIAN (gl) - core keys
# ============================================================
"gl": {
    "site_title": "✨ oratio",
    "return_home": "🏠 Volver a oratio.space",
    "invoice_copy_btn": "📋 Copiar",
    "invoice_back_btn": "🏠 Atrás",
    "error_title": "Algo saíu mal!",
    "success_title": "Pago Completado!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Sistema de Pago Bitcoin Cash",
},

# ============================================================
# OCCITAN (oc) - core keys
# ============================================================
"oc": {
    "site_title": "✨ oratio",
    "return_home": "🏠 Tornar a oratio.space",
    "invoice_copy_btn": "📋 Copiar",
    "invoice_back_btn": "🏠 Tornar",
    "error_title": "Quicòm a mal fo!",
    "success_title": "Pagament Acabat!",
    "about_contact": "oratio1809@proton.me",
    "footer_copyright": "© 2026 oratio - Sistèma de Pagament Bitcoin Cash",
},

}

# Also copy about_topic keys from custom-translations.json
ABOUT_KEYS = [f"about_topic_{i}_title" for i in range(1,9)] + [f"about_topic_{i}_desc" for i in range(1,9)] + ["about_contact"]

count = 0
for lang, trans in FULL.items():
    if lang not in data:
        data[lang] = {}
    for k, v in trans.items():
        if k not in data[lang]:
            data[lang][k] = v
            count += 1

# Copy about_topic from custom-translations.json for each language
for lang in data.keys():
    if lang in custom:
        for key in ABOUT_KEYS:
            if key in custom[lang] and key not in data[lang]:
                data[lang][key] = custom[lang][key]
                count += 1

with open('translations.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"✅ Added {count} missing Flask translation keys")
en_keys = list(data['en'].keys())
for lang in sorted(data.keys()):
    missing = len(en_keys) - len(data[lang])
    flag = f" (missing {missing})" if missing > 0 else " ✓"
    print(f"  {lang}: {len(data[lang])} keys{flag}")
