name: Lint Build Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: black --all-files

  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node dependencies with caching
        uses: actions/setup-node@v3
        with:
          node-version: "12"
          cache: "npm"

      - name: Build JS modules
        run: |
          npm install
          npm run build

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python dependencies with caching
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "poetry"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Run tests with Poetry
        run: |
          poetry install
          poetry run pytest
